pipeline {
  agent any
  environment {
    RELEASE='20.04'
  }
  stages {
    stage('Build') {
      agent any
      environment {
        LOG_LEVEL='INFO'
      }
      steps {
        echo "Builiding release ${RELEASE} with log level ${LOG_LEVEL}"
      }
    }
    stage('Test') {
      steps {
        echo "Testing. I can release ${RELEASE}, but log level"
      }
    }
    stage('Deploy') {
      input {
        message 'Deploy?'
        ok 'Do it!'
        parameters {
          string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: "Target deployment env")
        }
      }
      steps {
        echo "Deploying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
      }
    }
  }
  post {
    always {
      echo 'Prints success or failure'
    }
  }
}